In [9]:
# MODULE IMPORTS
# pip install modules in requirements.txt first
import pandas as pd

In [14]:
# DATA
df = pd.read_excel("aspe-uninsured-estimates-by-county.xlsx")

In [15]:
# EDA
all_uninsured.head(5)

,State Name,Total Non-Elderly Population (Excluding Undocumented),Uninsured Population (Excluding Undocumented),Percent Uninsured,HIU Income < 100% FPL,HIU Income 100-138% FPL,HIU Income 139-249% FPL,HIU Income 250-400% FPL,HIU Income 400% FPL,Age 0-18,...,College Grad,No English Speaking Adults in HH,English Spoken in HH,Spanish Spoken in HH,Chinese Spoken in HH,Korean Spoken in HH,Vietnamese Spoken in HH,Tagalog Spoken in HH,Russian Spoken in HH,Other Language Spoken in HH
0,Alabama,3986500,456100,0.11,213000,48800,94700,59100,40400,36800,...,37300,10000,442000,11600,600,200,**,**,**,1200
1,Alaska,629300,80300,0.13,21100,8100,22100,17900,11000,13300,...,10100,600,77600,1000,**,**,**,100,**,1300
2,Arizona,5720700,698800,0.12,220400,63200,196000,130000,89300,144800,...,104800,51500,625400,57200,1500,300,1200,**,200,12900
3,Arkansas,2443900,257200,0.11,88700,29500,79600,39800,19500,37600,...,18900,11000,243700,10500,**,**,**,**,**,2900
4,California,32060700,2397600,0.07,729900,196800,629300,447500,394000,325600,...,403100,340000,1808400,451900,32700,23700,14100,10100,3900,52900